security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: id
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                username_parameter: verify[id]
                password_parameter: verify[password]
                provider: my_provider
            logout:
                path: /logout
                target: /

    access_control:
        
        - { path: ^/login, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/register, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/, roles: ROLE_USER }




